---
- name: Install Dnsmasq
  apt:
    name: dnsmasq
    state: 'latest'
    install_recommends: False
  tags: dnsmasq

- name: Set configuration file
  template:
    src: etc_dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    validate: 'dnsmasq --test --conf-file=%s'
  notify: restart dnsmasq
  tags: dnsmasq

- name: Set additional hosts file
  template:
    src: etc_dnsmasq.hosts.j2
    dest: "{{ dnsmasq_addn_hosts_file }}"
  when: dnsmasq_addn_hosts is defined
  notify: restart dnsmasq
  tags: dnsmasq

- name: Make sure Dnsmasq is running
  service:
    name: dnsmasq
    state: started
    enabled: yes
  tags: dnsmasq
